### ISSUE TITLE
Release 1.0.0 does not contain lib. Contains sample project APK.

### ISSUE THREAD

**Issue by cauli** [vansikrishna/Multimager#1]
Hey Vansikrishna, thanks for developing this.

I'm following the instructions but it results in the following error

```
Warning:Dependency com.github.vansikrishna:Multimager:1.0.0 on project app resolves to an APK archive which is not supported as a compilation dependency. File: /Users/caulitomaz/.gradle/caches/modules-2/files-2.1/com.github.vansikrishna/Multimager/1.0.0/c0d0274794e84bf55f0737d4a16d87a9b131f195/Multimager-1.0.0.apk
```

It seems to me that the 1.0.0 release results in the sample project APK instead of importing the dependencies for this project. Am I doing something wrong?

Thank you

**Comment by vansikrishna** [comment]
I will recheck and update the same.

Thank you for updating me on this.

Regards
Vansi

**Comment by vansikrishna** [comment]
Support added to import as library. Version upgraded to 1.0.2.
