### ISSUE TITLE
CALL_PHONE

### ISSUE THREAD

**Issue by isorri** [vansikrishna/Multimager#17]
What do you need CALL_PHONE permission for?

**Comment by vansikrishna** [comment]
Hello,

That permission is needed to get the unique "device ID" details. Although
the permission name confuses the intention behind.

Vansi

**Comment by isorri** [comment]
Hello,

Thanks for the answer.
I think that It's not necessary request CALL_PHONE permission to get DEVICE_ID, you can get it with:
https://developer.android.com/about/versions/oreo/android-8.0-changes.html#privacy-all
https://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id

But, What do you need a unique device_id for?

**Comment by vansikrishna** [comment]
Hello,

Sorry i got confused. Phone call permission is for making calls itself. On
the demo activity i have two options for call and sms which redirects to my
number in case anyone would like to contact me directly other than email.

You don't have to use those permissions since its for the demo activity
only.

Vansi

**Comment by isorri** [comment]
Hi,
Ok!
Please move the permission request to [demo activity](https://github.com/vansikrishna/Multimager/blob/master/example/src/main/AndroidManifest.xml) instead of library one.
When I use the library, all the permissions that you declare in the library manifest are added to my app manifest automatically.

Another suggestion, use gradle dependency of Picasso instead of add the jar directly.
compile 'com.squareup.picasso:picasso:2.5.2'

Thanks!

**Comment by vansikrishna** [comment]
Ok. Sure. I will do it. Will update the lib in a day or two.

Vansi

**Comment by isorri** [comment]
Ok, thanks a lot! ^_^

**Comment by vansikrishna** [comment]
Removed the call phone permission in manifest. Also removed the call, msg feature from demo activity. Its not so important
