### ISSUE TITLE
Need help in changing the color of the toolbar

### ISSUE THREAD

**Issue by darshandawaibox** [vansikrishna/Multimager#8]
Your README file says that we can change the default colors by using the setViewsColorStateList from the Utils class. Could you give me a sample code for that? I have tried the following and it doesn't seem to work. 

```
Utils utils = new Utils();
utils.setViewsColorStateList(findViewById(com.vlk.multimager.R.id.toolbar),R.color.white,R.color.themeColor);
```

Also why doesn't the following code work?

```
params.setToolbarColor(R.color.white);
params.setActionButtonColor(R.color.white);
params.setButtonTextColor(R.color.colorAccent);
```

Please help me the above issues. Thanks

**Comment by vansikrishna** [comment]
1. The ReadMe file suggests that my `setViewsColorStateList()` in `Utils` class does the job of changing colors. You can copy the same for your project but the library will only act on the inputs passed through Params instance. However you can use the source code within the method `setViewsColorStateList()` in `Utils` class to change the colors as needed for your views.
2. The whole theme of this library is a AppCompat.Light.DarkActionBar, hence the base colors should be darker. You are trying to use white color, which wont work for this theme. White works for AppCompat.Dark.
3. In your given code, you are trying to set `R.color.white` as `params.setToolbarColor(int color);`. That R.color.white is not an actual color value but a reference to it. You should try 
`ContextCompat.getColor(this, R.color.colorAccent);` to fetch the color value as int and send it through Params.

**Comment by darshandawaibox** [comment]
Hi, Thank you for your help. Your suggestions helped. I have one more question though.
While the Image is loading there is a default "image is processing" with a spinner in the background. is there any way I can customize that?

**Comment by vansikrishna** [comment]
Sorry. You cant change it. Although you can copy all the source code and
modify the desired resources.

**Comment by vansikrishna** [comment]
I am closing this issue now.
