### ISSUE TITLE
Selected Images

### ISSUE THREAD

**Issue by brar07** [vansikrishna/Multimager#9]
If we have selected 2 images using this multimager and next time, if we start the intent and choose to select images from gallery, then previous selected images should automatically show as selected in gallery. How to do that?

**Comment by vansikrishna** [comment]
This library doesn't remember the previously picked images and hence continues to allow general selection. If you can copy this source code as part of your project then you can pass the previously picked image "ids" through Params instance. And modify the images adapter to disable the image selection if its "id" already exists in the previously selected list.

**Comment by vansikrishna** [comment]
Closing this issue since no updates recently.

**Comment by brar07** [comment]
Sorry for late reply, but can you tell which files to copy. I am guessing one is utils folder.
